title: blog
description: > # this means to ignore newlines until "baseurl:"
 백준우의 블로그 입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://junwoo0617.github.io"
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: junwoo
tagline: 환영합니다.
about-description: 저는 경동고 2학년 백준우 입니다.   # Add Discription



pic: OIP(1).jfif  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below



# Contact links
email: junwoobaek6405@gmail.com # Add your Email address
phone: 010 6405 7424 # Add your Phone number
website: artemsheludko.pw # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: junwoo0617 # Add your Github handle
instagram: '@junwoobaek_07' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:s
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
